platform :android do
  lane :lint do
    gradle(
      task: "ktlintCheck",
      project_dir: "./"
    )
  end

  lane :build do
    gradle(
      task: "composeApp:assembleDebug",
      project_dir: "./"
    )
  end
  
  lane :release do
    gradle(
      task: "composeApp:bundleRelease",
      project_dir: "./"
    )
  end

  lane :deploy do
  end

end

platform :ios do
  lane :build do
    gradle(
      task: "composeApp:linkDebugFrameworkIosArm64",
      project_dir: "./"
    )
    
  end

    lane :ios_release do
      gradle(
        task: "composeApp:linkReleaseFrameworkIosArm64",
        project_dir: "./"
      )
      build_app(
        project: './iosApp/iosApp.xcodeproj',
        scheme: "iosApp",
        configuration: "Release",
        destination: "generic/platform=iOS"
      )

    end

    lane :release do
        gradle(
          task: "composeApp:linkReleaseFrameworkIosArm64",
          project_dir: "./"
        )

        build_app(
          project: './iosApp/iosApp.xcodeproj',
          scheme: 'iosApp',
          configuration: 'Release',
          destination: 'generic/platform=iOS',
          allowProvisioningUpdates: true
        )
    end

end

